os:
  - osx

language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

env:
  - LANG=en_US.UTF-8

before_install:
  - export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - gem install bundler --no-ri --no-rdoc

install:
  - bundle install --without=debugging documentation --path ./travis_bundle_dir

  # CocoaPods/CocoaPods specific
  - ./bin/pod repo update --silent

script: rake spec

notifications:
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "qOE5zmgaHe/qQu3W9rmj7wygA5Ivl+cx50fqWGag2bdRl8ly5yj1NVoOKk/O\nZmQc4Lze+301uvTXi+r5v8A/tF6W1kUZw7yBiKuXoYFUGmDiVR9o2I/FPwkL\ngSzPJttrXTQfkQ4PbnrkX+JO+5bLWrKaO0hKXT4B2yUu4UXLVk0="
